version: "3"
services:
  web:
    image: organization-name/project-name # IMAGE_NAME value from circleci
    volumes:
      - .:/usr/src/vote21
    environment:
      ENV: development
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: "psql://postgres:postgres@db:5432/vote21"
    entrypoint: scripts/testing.sh
    depends_on: 
      - db

  db:
    image: circleci/postgres:9.6.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app